### ISSUE TITLE
Media names under next row in libraries 

### ISSUE THREAD

**Issue by p37307** [jellyfin/jellyfin-roku#47]
When you are viewing library folders, series/movie names are under the poster of the row below. I tested this in the current v1.0.5 version as well as the recent build I made when troubleshooting that audio codec issue the other day

**Comment by 1hitsong** [comment]
@p37307 Can you post a screenshot for me?

**Comment by p37307** [comment]
@1hitsong I meant to come back and do that. I circled the text under the next row's posters

![image](https://github.com/user-attachments/assets/00d4367f-af07-4947-89c9-7fdccf59e915)
