### ISSUE TITLE
Add music playback support

### ISSUE THREAD

**Issue by ae5960e8-a6fc-491f-b252-898ecf59af95** [jellyfin/jellyfin-roku#519]
**Is your feature request related to a problem? Please describe.**
If you try to open a library of music an error saying "This CollectionFolder has no items" shows.

**Describe the solution you'd like**
Implement the ability to choose albums and tracks to then play them similar to how TV and Movie librarys work with cover art.

**Comment by anthonylavado** [comment]
Duplicate of #124.
