### ISSUE TITLE
Viv 1.0.9 opens, then crashes and closes

### ISSUE THREAD

**Issue by p37307** [jellyfin/jellyfin-roku#81]
## Software Versions

- Jellyfin Server Version:  10.10.1
- Roku Client Version:  viv 1.0.9
- TV RTRU6528-C-CA (G000X)

## Describe the bug

Open Viv, first row starts appearing, Viv closes back to roku homescreen
## How To Reproduce

1. Roku Home screen
2. Click on Viv
3. Viv Opens
4. first row starts appearing, Viv closes back to roku homescreen

## Expected behavior

Viv doesn't crash
## Logs

This is the only thing that has to do with the session in the Jellyfin log that I can see. 

```
[2024-11-05 21:42:28.040 -05:00] [DBG] [30] Jellyfin.Networking.Manager.NetworkManager: Trying to get bind address for source "192.168.0.20" - External: False
[2024-11-05 21:42:28.042 -05:00] [DBG] [30] Jellyfin.Networking.Manager.NetworkManager: "192.168.0.20": No matching bind address override found
[2024-11-05 21:42:28.043 -05:00] [DBG] [30] Jellyfin.Networking.Manager.NetworkManager: "192.168.0.20": Internal request received, matching internal bind address found: "192.168.0.11"
[2024-11-05 21:42:28.052 -05:00] [DBG] [30] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was not authenticated.
[2024-11-05 21:42:28.054 -05:00] [DBG] [30] Jellyfin.Networking.Manager.NetworkManager: Trying to get bind address for source "192.168.0.20" - External: False
[2024-11-05 21:42:28.055 -05:00] [DBG] [30] Jellyfin.Networking.Manager.NetworkManager: "192.168.0.20": No matching bind address override found
[2024-11-05 21:42:28.056 -05:00] [DBG] [30] Jellyfin.Networking.Manager.NetworkManager: "192.168.0.20": Internal request received, matching internal bind address found: "192.168.0.11"
[2024-11-05 21:42:28.125 -05:00] [DBG] [30] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2024-11-05 21:42:28.128 -05:00] [DBG] [30] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2024-11-05 21:42:28.237 -05:00] [INF] [55] System.Net.Http.HttpClient.Default.ClientHandler: Received HTTP response headers after 433.5508ms - 200
[2024-11-05 21:42:28.239 -05:00] [INF] [55] System.Net.Http.HttpClient.Default.LogicalHandler: End processing HTTP request after 438.2212ms - 200
```

## Connection Information

- Is server local or remote? local
- Is server connection HTTP or HTTPS? http

## Additional context

After a couple attempts, I quickly press * and choose change servers, which I was able to do, and manually enter my local server IP and attempt to log in again, same thing happened after doing that. It loaded the top row, and then waited a second and abruptly closed.

Willing to sideload a beta test fix.

Willing to debug with Visual studio if you walk me how to.

**Comment by p37307** [comment]
I am thinking this is happening because the server is busy doing something, like scanning, importing a video, etc, and v1.0.9 crashes while waiting... I'm not sure, though. I was able to quickly press * and change servers to my test server, which doesn't have a large library and has scanning, trickplay, etc turned off and it connected fine...

**Comment by 1hitsong** [comment]
I was able to track it down. New release on the way.

**Comment by 1hitsong** [comment]
You should be able to sideload this release until the channel updates: https://github.com/1hitsong/viv/releases/tag/1.0.10

**Comment by p37307** [comment]
@1hitsong I sideloaded it. It froze on the "What's new" popup. Even makes Roku remote to get out to go to the Roku main screen locked for a few seconds. On second boot, it starts populating the top row and then freezes again. Even the Roku remote is unresponsive and won't go back to the default Roku home screen.

I restarted and I quickly pressed * and tried to change server and it froze halfway between change user and change server in the options. 

To make sure it wasn't my server, I opened in the official Jellyfin Roku app and it loaded fine.  I then sideloaded Viv10.0.8 and it loaded just fine.

First time, it froze at this screen.
![image](https://github.com/user-attachments/assets/4498fcab-09cc-478a-98d7-a9025978e0cf)

**Comment by 1hitsong** [comment]
Can you side load the code through VS Code and see if it throws any errors?

**Comment by p37307** [comment]
Yes. Can I side load. Do I need to compile it again or how do I side load it. I've never done it with a zip already. Please advise how to do it. the ip is 192.168.0.182 for the particular roku I will test on. 1.0.10 is already on the roku, btw

**Comment by 1hitsong** [comment]
The Jellyfin Roku dev guide has great instructions for loading from source code - just sub in the viv repo for it: https://github.com/jellyfin/jellyfin-roku/blob/master/docs/DEVGUIDE.md

In the meantime, what are the sections on your home screen? I wonder if you have a row that I don't, or a combination that I haven't seen.

**Comment by 1hitsong** [comment]
Also, can you try turning off each home section one-by-one and see if by turning one off it prevents the crash?

**Comment by p37307** [comment]
I will turn all the home sections off and re add one by one until it crashes. 
![image](https://github.com/user-attachments/assets/023d09ea-80ec-4850-8fd6-867bf1d09e1b)

Meanwhile, not sure if this is the output you want, but
Here's after vscode opened it: 
[vscode output.txt](https://github.com/user-attachments/files/17652946/vscode.output.txt)

I'll now try to disable sections and readd them.

**Comment by 1hitsong** [comment]
Thanks for the output! Something is attempting to load an image without a valid ID.

I just pushed a code change up to master. Try pulling the updated code and deploying again and see if it loads for you.

**Comment by p37307** [comment]
Ok, "recently added" caused it. I then disabled everything but recently added, and it froze by itself. Having all those sections, except Recently Added, the app opens

**Comment by 1hitsong** [comment]
I have a suspicion of what it could be. Let me know if things work using the updated code pull.

**Comment by p37307** [comment]
That seems to have fixed the issue I was having. Thanks for the quick response! Now to side load to the other 2 Roku's because no one is happy with the official one anymore. We're a Viv household.

**Comment by 1hitsong** [comment]
🤘 Killer! Glad that fixed it for ya'.

**Comment by p37307** [comment]
New issue, I've been using it and testing the side loaded version and when I go to Next Up in the version that I built above, and choose view all next up option, it lists every movie, video and episode I have in all libraries alphabetically. 

You want to continue to debug here or a new issue?

I can't debug right now as of the time I send this so my response may come in a few hours

**Comment by 1hitsong** [comment]
@p37307 Fixed! Updated code should fix View All Next Up.

**Comment by p37307** [comment]
@1hitsong Sorry it took so long. It did fix that issue. I'm going to continue to test different things and will get back to you if I find anything. Thanks for this project, btw!
